### ISSUE TITLE
License disposition

### ISSUE THREAD

**Issue by earl-ducaine** [ams/mit-cadr#4]
According to the license distributed with the MIT AI CADR tapes, MIT was releasing all the code under the conventional MIT license.  That should cover PROMS, Lisp code, and world images.  But I haven't been able to find any indication on whether Brad's original c code or any of ggilley's work his a license.  

Possible solutions would be to update the license in the project.  Alternately to prepare emulator code with a known license.  What are your thoughts on the license situation?

**Comment by ams** [comment]
MIT only relicensed the tapes for System 46, not later systems.  So that does not apply to any LOD bands, etc. See http://unlambda.com/mit/README . AFAIK.  As for usim, that is better to ask @lisper and @ggilley.

**Comment by earl-ducaine** [comment]
Disappointing to hear.  Thanks for the quick response!

Cheers.

**Comment by ams** [comment]
The licensing for the MIT CADR System software is solvable, Brad had good contact with MIT.  I don’t prioritize it since there is more interesting work to be done.  Would you like to give it a stab? Sorting out both the usim license and the system software would be quite nice.
